### ISSUE TITLE
colossalai.launch has error, but colossalai.launch_from_torch works well

### ISSUE THREAD

**Issue by Arsmart123** [hpcaitech/ColossalAI#181] opened 2022-01-21 14:52 UTC
### Describe the feature

I am running the code in NUS HPC. When I open two tab separately to run this command:

DATA='./dataset/' python train_1.py --world_size=2 --rank=0 --local_rank=0 --host='172.17.0.1' --port='51061' --config='./configs/vit_1d.py'

DATA='./dataset/' python train_1.py --world_size=2 --rank=1 --local_rank=1 --host='172.17.0.1' --port='51061' --config='./configs/vit_1d.py'

I will encounter an error like this:
File "/home/svu/e0XXXXXX/.conda/miniconda/envs/huang_test/lib/python3.6/site-packages/colossalai-0.0.1b0-py3.6.egg/colossalai/nn/layer/parallel_1d/_utils.py", line 211, in gather_forward_split_backward
    return _GatherForwardSplitBackward.apply(input_, parallel_mode, dim)
  File "/home/svu/e0XXXXXX/.conda/miniconda/envs/huang_test/lib/python3.6/site-packages/colossalai-0.0.1b0-py3.6.egg/colossalai/nn/layer/parallel_1d/_utils.py", line 137, in forward
    return _gather(input_, parallel_mode, dim)
  File "/home/svu/e0XXXXXX/.conda/miniconda/envs/huang_test/lib/python3.6/site-packages/colossalai-0.0.1b0-py3.6.egg/colossalai/nn/layer/parallel_1d/_utils.py", line 71, in _gather
    torch.distributed.all_gather(tensor_list, input_, group=gpc.get_group(parallel_mode))
  File "/home/svu/e0XXXXXX/.conda/miniconda/envs/huang_test/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 2006, in all_gather
    work = group.allgather([tensor_list], [tensor])
RuntimeError: NCCL error in: ../torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:957, internal error, NCCL version 21.0.3
ncclInternalError: Internal check failed. This is either a bug in NCCL or due to memory corruption

But when I use torchrun version like this:
DATA='./dataset/' torchrun  --nproc_per_node=2   --nnodes=1  --node_rank=0   --master_addr='172.17.0.1'     --master_port='51066'  train_1.py --config='./configs/vit_1d.py'

It works well! 

Just doubt why, haha. Any suggestion will benefit me and broadcast knowledge, thanks!

**Comment by FrankLeeeee** [comment] 2022-01-24 05:03
Interesting problem. Can you tell me your environment so that I can try to reproduce this error? e.g. Python version, PyTorch version, CUDA version, etc 😃

**Comment by FrankLeeeee** [comment] 2022-01-28 08:01
Hi  @Arsmart123 , do you still have this issue？

**Comment by Arsmart123** [comment] 2022-01-28 08:12
> Hi @Arsmart123 , do you still have this issue？

Thank you for your attention!! Actually I am also in HPCAI group and we can use wechat if you like.
I did not try torch.launch for now, but definitely necessary in the future because only NSCC has multiple GPUs~
My environment for NSCC is pytorch 1.8+cuda10.1+python3.6.
If you would like to try my code, I can send you the code!
Thank you very much!!!
Happy CNY!

**Comment by FrankLeeeee** [comment] 2022-01-28 08:16
Sure, I am more than willing to see what the root cause is. If you have a public repository for your code, you can share it with me. I will try to reproduce this error. One thing I note is that you use CUDA 10.1 for pytorch 1.8. I think the CUDA version PyTorch binary was built with is CUDA 10.2. Not sure if this causes the issue.

**Comment by Arsmart123** [comment] 2022-01-29 04:21
1. Seems must use python3.7 or upper, because lower version like 3.6 will have error: can not import **nullcontext**
2. Current environment I am using is: python3.7, torch1.8+cu101(restricted by NSCC device), pip install colossalai(not build from source code), and I get this error message:

(new_colossalai) eXXXXXXX@dgx4105:~/test_delete/ColossalAI-main/benchmark$ DATA='./dataset/' python train.py --world_size=2 --rank=1 --local_rank=1ost='172.17.0.1' --port='51061' --config='./configs/vit_1d.py'
Colossalai should be built with cuda extension to use the FP16 optimizer
Colossalai should be built with cuda extension to use the FP16 optimizer
DeepSpeed is required if you want to use ZeRO.
DeepSpeed is required if you want to use ZeRO.
apex is required for mixed precision training
Traceback (most recent call last):
  File "train.py", line 12, in <module>
    from colossalai.nn import Accuracy, CrossEntropyLoss
ImportError: cannot import name 'Accuracy' from 'colossalai.nn' (/home/users/nus/eXXXXXXX/anaconda3/envs/new_colossalai/lib/python3.7/site-packages/colossalai/nn/__init__.py)

3. Haha, luckily I saved the old version of Colossalai and that should work. Thank you for your attention!!

**Comment by FrankLeeeee** [comment] 2022-02-03 02:00
Hi, the 1st issue will be fixed in the coming PR. The 2nd issue is that you need to build from source.

**Comment by FrankLeeeee** [comment] 2022-02-08 02:29
Hi, the solution seems ok? I will close this issue for now. You can reopen this issue if the problem persists. :)

**Closed by FrankLeeeee** 2022-02-08 02:29 UTC

**Comment by Arsmart123** [comment] 2022-02-12 02:21
Thank you!!! I am just busy doing other stuff recently…

Frank Lee ***@***.***
