### ISSUE TITLE
[BUG]: 

### ISSUE THREAD

**Issue by thatguymiller** [hpcaitech/ColossalAI#4181] opened 2023-07-05 15:23 UTC
### 🐛 Describe the bug

Non mi fa usare la chat

**Comment by thatguymiller** [comment] 2023-07-05 15:34
ho scritto "hello" ma non ha funzionato

**Comment by thatguymiller** [comment] 2023-07-05 15:40
quando cerco di farlo mi appare questo messaggio The service has been taken down by our team, please visit our GitHub for more information at https://github.com/hpcaitech/ColossalAI/tree/main/applications/Chat

**Comment by thatguymiller** [comment] 2023-07-05 15:46
allora?

**Comment by thatguymiller** [comment] 2023-07-05 15:48
come faccio a risolverlo?

**Comment by thatguymiller** [comment] 2023-07-05 15:51
ho scritto in inglese, ma non funzionava comunque

**Comment by thatguymiller** [comment] 2023-07-05 15:53
e quale lingua è il problema?

**Comment by thatguymiller** [comment] 2023-07-05 15:54
quindi devi scrivere tutto in inglese?

**Comment by thatguymiller** [comment] 2023-07-05 15:57
perché mentre provo a scrivere compare la scritta "il servizio è stato rimosso dal nostro team"?

**Comment by thatguymiller** [comment] 2023-07-05 16:10
vaffanculo

**Comment by thatguymiller** [comment] 2023-07-05 16:12
è l'italiano?

**Comment by Gy-Lu** [comment] 2023-07-06 02:43
Hi, If you met some problems or bugs when using Colossal-AI, please describe which kinds of functions you are using, what is the error message and what it should be and tell us your environment to help us reproduce and locate the problem.

And here is the answer to your problem:
Since this message `The service has been taken down by our team`, I guess you are visiting https://chat.colossalai.org/ .
However, the service is not in online using. But you can train your own one with Colossal-AI.

And I would close this issue. If you have other questions, feel free to open a new one.

Puoi tradurre la nostra risposta in inglese sopra in italiano (tramite google translate)

**Closed by Gy-Lu** 2023-07-06 02:43 UTC
Labels: bug

**Comment by thatguymiller** [comment] 2023-07-06 11:24
perché non mi fa usare colossal?

**Comment by thatguymiller** [comment] 2023-07-06 11:27
in quale lingua?

**Comment by thatguymiller** [comment] 2023-07-06 11:28
ho scritto in inglese, ma non me lo fa usare comunque

**Comment by thatguymiller** [comment] 2023-07-06 11:28
il bot ha rilevato l'italiano come lingua?

**Comment by Gy-Lu** [comment] 2023-07-06 13:01
`colossal` is the name of the repo, and it is a framework to accelerate the training and inference of neural networks.

This website `https://chat.colossalai.org/` is a trial with limited time. Now it is closed, and would not respond to anyone in any language.
We would release news if we offer a trial again. If you want to use it, be our guest at that time.
